-- Config qui vient de : https://github.com/alpha2phi/modern-neovim/ 
-- local M = {
--     {
--         "mfussenegger/nvim-dap",
--         dependencies = {
--             { "rcarriga/nvim-dap-ui" },
--             { "theHamsta/nvim-dap-virtual-text" },
--             { "nvim-telescope/telescope-dap.nvim" },
--             { "jbyuki/one-small-step-for-vimkind" },
--             { "jay-babu/mason-nvim-dap.nvim" },
--         },
--         -- stylua: ignore
--         -- Je comptais modifier les keys initiales mais en vrai elles font sens
--         keys = {
--             { "<leader>dR", function() require("dap").run_to_cursor() end, desc = "Run to Cursor", },
--             { "<leader>dE", function() require("dapui").eval(vim.fn.input "[Expression] > ") end, desc = "Evaluate Input", },
--             { "<leader>dC", function() require("dap").set_breakpoint(vim.fn.input "[Condition] > ") end, desc = "Conditional Breakpoint", },
--             { "<leader>dU", function() require("dapui").toggle() end, desc = "Toggle UI", },
--             { "<leader>db", function() require("dap").step_back() end, desc = "Step Back", },
--             { "<leader>dc", function() require("dap").continue() end, desc = "Continue", },
--             { "<leader>dd", function() require("dap").disconnect() end, desc = "Disconnect", },
--             { "<leader>de", function() require("dapui").eval() end, mode = {"n", "v"}, desc = "Evaluate", },
--             { "<leader>dg", function() require("dap").session() end, desc = "Get Session", },
--             { "<leader>dh", function() require("dap.ui.widgets").hover() end, desc = "Hover Variables", },
--             { "<leader>dS", function() require("dap.ui.widgets").scopes() end, desc = "Scopes", },
--             { "<leader>di", function() require("dap").step_into() end, desc = "Step Into", },
--             { "<leader>do", function() require("dap").step_over() end, desc = "Step Over", },
--             { "<leader>dp", function() require("dap").pause.toggle() end, desc = "Pause", },
--             { "<leader>dq", function() require("dap").close() end, desc = "Quit", },
--             { "<leader>dr", function() require("dap").repl.toggle() end, desc = "Toggle REPL", },
--             { "<leader>ds", function() require("dap").continue() end, desc = "Start", },
--             { "<leader>dt", function() require("dap").toggle_breakpoint() end, desc = "Toggle Breakpoint", },
--             { "<leader>dx", function() require("dap").terminate() end, desc = "Terminate", },
--             { "<leader>du", function() require("dap").step_out() end, desc = "Step Out", },
--         },
--         opts = {
--             setup = {
--                 osv = function(_, _)
--                     require("plugins.dap.lua").setup()
--                     -- Je viens de rajouter ce qui suit en me basant sur l'analyse du setup du lua.lua
--                     require("plugins.dap.cpp").setup()
--                 end,
--             },
--         },
--         config = function(plugin, opts)
--             require("nvim-dap-virtual-text").setup {
--                 commented = true,
--             }
--
--             local dap, dapui = require "dap", require "dapui"
--             dapui.setup {}
--
--             dap.listeners.after.event_initialized["dapui_config"] = function()
--                 dapui.open()
--             end
--             dap.listeners.before.event_terminated["dapui_config"] = function()
--                 dapui.close()
--             end
--             dap.listeners.before.event_exited["dapui_config"] = function()
--                 dapui.close()
--             end
--
--             -- set up debugger a partir de la liste de debugger que j'ai dans le dossier
--             for k, _ in pairs(opts.setup) do
--                 opts.setup[k](plugin, opts)
--             end
--         end,
--     },
--     --TODO: to configure mais je ne sais meme plus a quoi ce sert, up to date with what's on github
--     {
--         "jay-babu/mason-nvim-dap.nvim",
--         dependencies = "mason.nvim",
--         cmd = { "DapInstall", "DapUninstall" },
--         opts = {
--             automatic_setup = true,
--             handlers = {},
--             ensure_installed = {},
--         },
--     },
-- }
--
-- return M
